{
 "title": "SRCDS",
 "description": "Displays metrics collected using srcds_exporter.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "query": {
     "query": "label_values(srcds_status_connected, server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$server_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_stats_online{server=\"$server_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metamod enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_stats_metamod_version{server=\"$server_name\"})"
    }
   ]
  },
  {
   "title": "Sourcemod state",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_stats_sourcemod_version{server=\"$server_name\"})"
    }
   ]
  },
  {
   "title": "Players count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_status_players_human{server=\"$server_name\"})",
     "legendFormat": "Players"
    },
    {
     "expr": "sum by(server) (srcds_status_players_bots{server=\"$server_name\"})",
     "legendFormat": "Bots"
    },
    {
     "expr": "sum by(server) (srcds_stats_sv_visiblemaxplayers{server=\"$server_name\"})",
     "legendFormat": "Max players"
    }
   ]
  },
  {
   "title": "SourceTV status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_stats_source_tv{server=\"$server_name\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Tick" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "srcds_stats_sv_max_update_rate{server=\"$server_name\"}"
    }
   ]
  },
  {
   "title": "Metamod version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "srcds_stats_metamod_version{server=\"$server_name\"}",
     "legendFormat": "{{metamod_version}}"
    }
   ]
  },
  {
   "title": "Sourcemod version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "srcds_stats_sourcemod_version{server=\"$server_name\"}",
     "legendFormat": "{{sourcemod_version}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(server) ((srcds_stats_net_in{server=\"$server_name\"})*8)",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum by(server) ((srcds_stats_net_out{server=\"$server_name\"})*8)",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Players count (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(server) ((srcds_status_players_bots{server=\"$server_name\"})/srcds_stats_sv_visiblemaxplayers{server=\"$server_name\"}*100)",
     "legendFormat": "Bots"
    },
    {
     "expr": "sum by(server) ((srcds_status_players_human{server=\"$server_name\"})/srcds_stats_sv_visiblemaxplayers{server=\"$server_name\"}*100)",
     "legendFormat": "Players"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_stats_fps{server=\"$server_name\"})",
     "legendFormat": "FPS"
    }
   ]
  },
  {
   "title": "Players count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(server) (srcds_status_players_bots{server=\"$server_name\"})",
     "legendFormat": "bots"
    },
    {
     "expr": "sum by(server) (srcds_status_players_count{server=\"$server_name\"})",
     "legendFormat": " players"
    }
   ]
  }
 ]
}