name: build

on:
  push:
    branches:
      - master
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Install Analyzer Dependencies
        run: make check_deps

      #- name: Lint golangci-lint
      #  run: make lint_golangci

      - name: Lint vet
        run: make lint_vet

      - name: Lint imports
        run: make lint_imports

      - name: Lint cyclo
        run: make lint_cyclo

      - name: Lint golint
        run: make lint_golint

      - name: Lint static
        run: make static

  test:
    runs-on: ubuntu-latest
    name: Test
    environment: release
    needs: lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Test
        run: make test

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Publish image
    environment: release
    needs: test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
