name: Release Hub

on:
  push:
    tags:
      - 'v*'
    branches:
      - '*'
  pull_request:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

        - uses: goreleaser/goreleaser-action@v5
             if: success() && startsWith(github.ref, 'refs/tags/')
             with:
               distribution: goreleaser
               version: latest
               args: release --clean
             env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

           - name: Build & publish gbans image
             run: |
               docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}
               docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF##*/}

      - name: Upload snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: dist/*
          retention-days: 1
