name: linter

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install Analyzer Dependencies
        run: make check_deps

      - name: Lint golangci-lint
        run: make lint_golangci

      - name: Lint static
        run: make static
