name: tests

on:
  workflow_run:
    workflows: [linter]
    types:
      - completed

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          go-version: 'stable'
      - name: Test
        run: make test
